apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fitness-tracker-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shaan708820/fitness-tracker.git'
    targetRevision: HEAD
    path: fitness-tracker
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true