apiVersion: v1
kind: ConfigMap
metadata:
  name: fitness-config
data:
  MONGO_HOST: "mongodb-service"
  PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: fitness-secrets
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "securepassword123"